# Use postgres/example user/password credentials
version: '3.1'

services:

  pgdb:
    image: postgres:10.5
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: EXAMPLE_INIT_PASSWORD
    command:
      - postgres
      - -c 
      - 'config_file=/etc/postgresql/postgresql.conf'
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080